# <3 Thank you for downloading ^0^ Pls visit my github - https://github.com/wolfykq and star this repo :)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  MAIN MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/monitor.conf
source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/animations.conf
source = ~/.config/hypr/hyprland/settings.conf

workspace = 9, layoutopt:layout:dwindle
workspace = 10, layoutopt:layout:dwindle
workspace = 9, decorate:false, blur:false, gapsin:0, gapsout:0
workspace = 10, decorate:false, blur:false, gapsin:0, gapsout:0
workspace = 9, animate:false
workspace = 10, animate:false