# <3 Thank you for downloading ^0^ Pls visit my github - https://github.com/wolfykq and star this repo :)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  MAIN MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

source = ~/.config/hypr/hyprlock/labels.conf
source = ~/.config/hypr/hyprlock/input_field.conf
source = ~/.config/hypr/hyprlock/settings.conf