# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  AUTOSTART
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

$wallpaper = awww-daemon && awww img ~/Customizations/Mountain.jpg --transition-type fade --transition-fps 240
$cursor = hyprctl setcursor Bibata-Modern-Classic 22

exec-once = $wallpaper
exec-once = waybar
exec-once = $cursor
exec-once = hyprlock