general {
    layout = scrolling

    gaps_in = 4
    gaps_out = 10
    border_size = 1

    col.active_border = rgb(e8eef2) rgb(52535A) 295deg
    col.inactive_border = rgb(040406)
    
    allow_tearing = true
}

misc {
    vrr = 1
}

scrolling {
    column_width = 1
    fullscreen_on_one_column = true
    direction = right
}

input {
    kb_layout = us,ru
    kb_options = grp:ctrl_shift_toggle
    sensitivity = 0.3
    accel_profile = flat
}

device {
    name = attack-shark-r5-ultra-mouse-2.4g
    
    sensitivity = 0.0
    accel_profile = flat
}

decoration {
    rounding = 10

    active_opacity = 1
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
    }
    shadow {
        enabled = true
    }
}