# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  INPUT FIELD CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ---------------------------
#  PASSWORD INPUT FIELD
# ---------------------------
input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2
    dots_text_format = 々
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    check_color = rgba(255, 0, 0, 0.6)
    outer_color = rgba(22,28,36,0.5)
    inner_color = rgba(22,28,36,0.5)
    font_color = rgba(194,199,202,0.8)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <span foreground="##6E7478">$USER</span>
    hide_input = false
    position = 0, -250
    halign = center
    valign = center
}