# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  LABELS CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ---------------------------
#  TIME
# ---------------------------
label {
    monitor =
    text = cmd[update:1000] sh ~/.config/hypr/hyprlock/scripts/current_time.sh
    color = rgba(245,248,250,1)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, 200
    halign = center
    valign = center
}

# ---------------------------
#  DATE
# ---------------------------
label {
    monitor =
    text = cmd[update:1000] sh ~/.config/hypr/hyprlock/scripts/current_date.sh
    color = rgba(138,160,176,1)
    font_size = 15
    font_family = JetBrains Mono Extrabold
    position = 0, 120
    halign = center
    valign = center
}

# ---------------------------
#  CURRENT SONG
# ---------------------------
label {
    monitor =
    text = cmd[update:1000] sh ~/.config/hypr/hyprlock/scripts/current_song.sh
    color = rgba(61,65,69,1)
    font_size = 12
    font_family = SF Pro Display Bold
    position = 0, -505
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] cava
    color = rgba(245,248,250,1)
    font_size = 95
    font_family = JetBrains Mono Extrabold
    position = 0, -50
    halign = center
    valign = center
}
